import {
  Home,
  ChefHat,
  ShoppingCart,
  Package,
  Tag,
  TrendingUp,
  User,
  Utensils,
  Apple,
  ListOrdered,
} from "lucide-react";

export const managerSidebarData = {
  user: {
    name: "Manager User",
    email: "manager@chickenkitchen.com",
    avatar: "/src/assets/img/Logo.png",
  },
  navMain: [
    {
      title: "Dashboard",
      url: "/manager/dashboard",
      icon: Home,
      description: "Overview & analytics",
      badge: undefined,
    },
    {
      title: "Categories",
      url: "/manager/categories",
      icon: Tag,
      description: "Menu categories",
      badge: undefined,
    },
    {
      title: "Menu Items",
      url: "/manager/menu-items",
      icon: ChefHat,
      description: "Manage dishes",
      badge: undefined,
    },
    {
      title: "Orders",
      url: "/manager/orders",
      icon: ShoppingCart,
      description: "Order management",
      badge: "New",
    },
    {
      title: "Ingredients",
      url: "/manager/ingredients",
      icon: Package,
      description: "Inventory",
      badge: undefined,
    },
    {
      title: "Dishes",
      url: "/manager/dishes",
      icon: Utensils,
      description: "Predefined dishes",
      badge: undefined,
    },
    {
      title: "Promotions",
      url: "/manager/promotions",
      icon: TrendingUp,
      description: "Special offers",
      badge: undefined,
    },
    {
      title: "Nutrients",
      url: "/manager/nutrients",
      icon: Apple,
      description: "Nutritional info",
      badge: undefined,
    },
    {
      title: "Recipe Steps",
      url: "/manager/steps",
      icon: ListOrdered,
      description: "Cooking instructions",
      badge: undefined,
    },
    {
      title: "Profile",
      url: "/manager/profile",
      icon: User,
      description: "My profile settings",
      badge: undefined,
    },
  ],
};
